# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jtpck < Formula
  desc "CLI tool for configuring OpenTelemetry in Claude Code, Codex, and Gemini CLI"
  homepage "https://github.com/jessewaites/jtpck-installer"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jessewaites/jtpck-installer/releases/download/v0.1.5/jtpck-installer_Darwin_x86_64.tar.gz"
      sha256 "dfba224ec13bcea3bd0e731435a45d67fcb66333d0f6f718b2f257cd2eb9c9de"

      def install
        bin.install "jtpck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jessewaites/jtpck-installer/releases/download/v0.1.5/jtpck-installer_Darwin_arm64.tar.gz"
      sha256 "7af06dfe84d7e3ca100c44f068c08746d82503faa7153f8ccc04b41ab27f6ca7"

      def install
        bin.install "jtpck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jessewaites/jtpck-installer/releases/download/v0.1.5/jtpck-installer_Linux_x86_64.tar.gz"
      sha256 "d8f8ca800b15986f668ffaee16576158c7a4b736984d0e05b0e748f4fe72e65d"
      def install
        bin.install "jtpck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jessewaites/jtpck-installer/releases/download/v0.1.5/jtpck-installer_Linux_arm64.tar.gz"
      sha256 "bd401f2a074d57efdb2bae4931da4e579278d5345a48df1245bb1d85e25c4ebb"
      def install
        bin.install "jtpck"
      end
    end
  end

  test do
    system "#{bin}/jtpck", "--version"
  end
end
