# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jtpck < Formula
  desc "CLI tool for configuring OpenTelemetry in Claude Code, Codex, and Gemini CLI"
  homepage "https://github.com/jessewaites/jtpck-installer"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jessewaites/jtpck-installer/releases/download/v0.1.2/jtpck-installer_Darwin_x86_64.tar.gz"
      sha256 "02aa943b2c49aa5957e7da79d6834451dee792739374deb7f2923a60097050a0"

      def install
        bin.install "jtpck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jessewaites/jtpck-installer/releases/download/v0.1.2/jtpck-installer_Darwin_arm64.tar.gz"
      sha256 "8c20770ed334960a6ac5079bc807bb9809713a378c67d39106a1240054921a63"

      def install
        bin.install "jtpck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jessewaites/jtpck-installer/releases/download/v0.1.2/jtpck-installer_Linux_x86_64.tar.gz"
      sha256 "21b5f2c95a4999d2a1718ec9a59f7733eb74025ff0d3feab27a4ed26061cb9c8"
      def install
        bin.install "jtpck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jessewaites/jtpck-installer/releases/download/v0.1.2/jtpck-installer_Linux_arm64.tar.gz"
      sha256 "cabbd626966896671ecd363e42141acfc1dc4e16ae72edf24360318e2a959b70"
      def install
        bin.install "jtpck"
      end
    end
  end

  test do
    system "#{bin}/jtpck", "--version"
  end
end
